### ISSUE TITLE
Adding cable modeling to the NodeConstructor

### ISSUE THREAD

**Issue by MarvinMeyer** [upb-lea/dare#13]
This issue is intended to add cable modeling to the NodeConstructor. First, the ODEs of the network for the 2 source 1 load case are derived and transferred to the state space representation. Based on this preliminary work, the generation of the matrices in the NodeConstructor is then adapted.

**Comment by Webbah** [comment]
### Results

Regarding the cable modeling of the NodeConstructor, a decision had to be made between the Pi and T equivalent circuit of the cables. These include the capacitance coatings Cb, the operating inductance Lb and the AC resistance Rb. Both represent the physical properties in the same way.
It turned out that the Pi equivalent circuit had a clear advantage in the case of multiple cable connections at a system node.  For the Pi equivalent circuit, the capacities can be combined in parallel and states can thus be kept small. 
Therefore the PI model is used and implemented in the nodeconstructor
